export const GET_TODO_REQUEST = "GET_TODO_REQUEST";
export const GET_TODO_SUCESS = "GET_TODO_SUCESS";
export const GET_TODO_FAILURE = "GET_TODO_FAILURE";

export const ADD_TODO_SUCESS = "ADD_TODO_SUCESS";
export const ADD_TODO_REQUEST = "ADD_TODO_REQUEST";
export const ADD_TODO_FAILURE = "ADD_TODO_FAILURE";

export const DELETE_TODO_REQUEST = "DELETE_TODO_REQUEST";
export const DELETE_TODO_SUCESS = "DELETE_TODO_SUCESS";
export const DELETE_TODO_FAILURE = "DELETE_TODO_FAILURE";

export const TOGGLE_TODO_REQUEST = "TOGGLE_TODO_REQUEST";
export const TOGGLE_TODO_SUCESS = "TOGGLE_TODO_SUCESS";
export const TOGGLE_TODO_FAILURE = "TOGGLE_TODO_FAILURE";

export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_SUCESS = "SEARCH_SUCESS";
export const SEARCH_FAILURE = "SEARCH_FAILURE";
// export const ADD_TODO = "ADD_TODO";
export const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER";

export const SHOW_COMPLETED_ITEMS = "SHOW_COMPLETED_ITEMS";
export const SHOW_NOT_COMPLETES_ITEMS = "SHOW_NOT_COMPLETES_ITEMS";
