const actions = {
	GET_TODO_REQUEST: "GET_TODO_REQUEST",
	GET_TODO_SUCESS: "GET_TODO_SUCESS",
	GET_TODO_FAILURE: "GET_TODO_FAILURE",

	ADD_TODO_SUCESS: "ADD_TODO_SUCESS",
	ADD_TODO_REQUEST: "ADD_TODO_REQUEST",
	ADD_TODO_FAILURE: "ADD_TODO_FAILURE",

	DELETE_TODO_REQUEST: "DELETE_TODO_REQUEST",
	DELETE_TODO_SUCESS: "DELETE_TODO_SUCESS",
	DELETE_TODO_FAILURE: "DELETE_TODO_FAILURE",

	TOGGLE_TODO_REQUEST: "TOGGLE_TODO_REQUEST",
	TOGGLE_TODO_SUCESS: "TOGGLE_TODO_SUCESS",
	TOGGLE_TODO_FAILURE: "TOGGLE_TODO_FAILURE",

	SEARCH_REQUEST: "SEARCH_REQUEST",
	SEARCH_SUCESS: "SEARCH_SUCESS",
	SEARCH_FAILURE: "SEARCH_FAILURE",
	// export const ADD_TODO = "ADD_TODO";
	SET_VISIBILITY_FILTER: "SET_VISIBILITY_FILTER",

	SHOW_COMPLETED_ITEMS: "SHOW_COMPLETED_ITEMS",
	SHOW_NOT_COMPLETES_ITEMS: "SHOW_NOT_COMPLETES_ITEMS",
};
export default actions;
