// const ACTIONS = {
// 	// GET_ALL_TODOS: "GET_ALL_TODOS",
// 	GET_TODO_REQUEST: "GET_TODO_REQUEST",
// 	GET_TODO_SUCESS: "GET_TODO_SUCESS",
// 	GET_TODO_FAILURE: "GET_TODO_FAILURE",

// 	ADD_TODO: "ADD_TODO",

// 	DELETE_TODO: "DELETE_TODO",
// 	TOGGELE_TODO: "toggleTodo",
// };
// export default ACTIONS;

export const GET_TODO_REQUEST = "GET_TODO_REQUEST";
export const GET_TODO_SUCESS = "GET_TODO_SUCESS";
export const GET_TODO_FAILURE = "GET_TODO_FAILURE";
export const ADD_TODO_SUCESS = "ADD_TODO_SUCESS";
export const ADD_TODO_REQUEST = "ADD_TODO_REQUEST";
export const ADD_TODO_FAILURE = "ADD_TODO_FAILURE";

// export const ADD_TODO = "ADD_TODO";
